# Generated by Django 5.1.6 on 2025-03-06 05:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillarWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='trabajo',
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyecto/')),
                ('url', models.CharField(max_length=500)),
                ('creacion', models.DateField(auto_now=True, verbose_name='Creacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChillarWeb.servicio')),
            ],
            options={
                'unique_together': {('email', 'name')},
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ChillarWeb.proyecto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Proyectos',
        ),
    ]
