# Generated by Django 5.1.6 on 2025-03-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillarWeb', '0003_pagina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina',
            name='id',
        ),
        migrations.AlterField(
            model_name='pagina',
            name='titulo',
            field=models.CharField(choices=[('Inicio', 'Inicio'), ('Servicios', 'Servicios'), ('Portafolio', 'Portafolio'), ('Equipo', 'Equipo')], max_length=255, primary_key=True, serialize=False),
        ),
    ]
