# Generated by Django 5.1.6 on 2025-03-07 20:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillarWeb', '0004_remove_pagina_id_alter_pagina_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='descipcion',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagina',
            name='texto',
            field=models.CharField(max_length=255),
        ),
    ]
