# Generated by Django 5.1.6 on 2025-03-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillarWeb', '0005_pagina_descipcion_alter_pagina_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='descipcion',
            field=models.TextField(null=True),
        ),
    ]
