# Generated by Django 5.1.6 on 2025-03-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillarWeb', '0006_alter_pagina_descipcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina',
            name='descipcion',
        ),
        migrations.AddField(
            model_name='pagina',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
