# Generated by Django 5.1.6 on 2025-03-07 21:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillarWeb', '0007_remove_pagina_descipcion_pagina_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('trabajo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('linkedin', models.CharField(max_length=150)),
                ('github', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='pagina',
            name='titulo',
            field=models.CharField(choices=[('Inicio', 'Inicio'), ('Servicios', 'Servicios'), ('Portafolio', 'Portafolio'), ('Equipo', 'Equipo'), ('Servicios', 'Servicio')], max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='desarrollador',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ChillarWeb.desarrollador'),
            preserve_default=False,
        ),
    ]
