# Generated by Django 5.1.6 on 2025-03-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillarWeb', '0008_desarrollador_alter_pagina_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
