# Generated by Django 5.1.6 on 2025-03-08 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChillarWeb', '0009_alter_proyecto_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='desarrollador',
        ),
    ]
