# Generated by Django 5.1.6 on 2025-03-08 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChillarWeb', '0010_remove_proyecto_desarrollador'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='desarrollador',
            field=models.ForeignKey(default=44393800, on_delete=django.db.models.deletion.CASCADE, to='ChillarWeb.desarrollador'),
            preserve_default=False,
        ),
    ]
